### ISSUE TITLE
When no room created for the page - suggest creating/selecting a room on attempt to create a highlight 

### ISSUE THREAD

**Issue by Stvad** [DanilaFe/matrix-highlight#23]
Right now clicks on the highlight buttons are just ignored and user does not get any feedback on what is wrong. 

A mild improvement would be to show an error saying they need to create a room. 

Ideally that interaction would just bring up "create/select a room" window, so user can rectify situation straight away. 

Potentially automatically creating a room can also be a good option (though need to think about this one more)

**Comment by DanilaFe** [comment]
Hi!

First of all, thanks for giving Matrix Highlight a go, and for taking the time to file issues! I really appreciate it. I agree that the color buttons should somehow communicate that a highlighting room hasn't been created. It shouldn't be too hard to bring up the "create room" menu.

I'm wary of automatically creating a room for reasons of pollution (does the user share their regular matrix account with matrix-highlight? If they do, do they really want tons of rooms auto-created without their explicit confirmation?) and due to potential interactions (I suspect that `#links-to-ids` might lead to the creation of tons of new rooms for a single page).

**Comment by Stvad** [comment]
> First of all, thanks for giving Matrix Highlight a go, and for taking the time to file issues! I really appreciate it

Thanks for building it, excited that it exists :) I re-derived the idea by myself and was excited to find out that someone already built it! 

> I'm wary of automatically creating a room for reasons of pollution

That is fair, this is worth thinking through in more detail. Plausibly having a separate space for these rooms helps!

> I suspect that #links-to-ids might lead to the creation of tons of new rooms for a single page

plausibly it makes sense to truncate the hash part of url for the purposes of identification?

**Comment by DanilaFe** [comment]
This is closed by #31 I believe.
